wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: Car-Racer-V2
batch_size:
  desc: null
  value: 64
latent_dims:
  desc: null
  value: 32
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1746488534.0
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
